name: Issues Test
on:
  issues:
    types: [opened, edited]
jobs:
  log:
    name: Log thing when new issue made
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Git config
        run: |
          git config user.name "Dimboard Actions"
          git config user.email ""

      - name: Get issue
        run: curl -H "Accept: application/vnd.github.v3+json" "$REPO_URL/$ISSUE_NUMBER"
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPO_URL: ${{ github.event.issue.repository_url }}



