name: Issues Test
on:
  issues:
    types: [opened, edited]
jobs:
  log:
    name: Log thing when new issue made
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Git config
        run: |
          git config user.name "Dimboard Actions"
          git config user.email ""

      - name: Add pin
        run: node .github/scripts/add-pin.js "$PINS_PATH" "$ISSUE_BODY"
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
          PINS_PATH: "pins.json"

      - name: Check output
        run: git show

      - name: Commit changes
        run: git add . && git commit -m 'Add new pin'

      - name: Push changes
        run: git push

