name: Issues Test
on:
  issues:
    types: [opened, edited]
jobs:
  log:
    name: Log thing when new issue made
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: What's the issue about
        env:
            EVENT: ${{ toJSON(github.event) }}
        run: echo "$EVENT"

