name: Issues Test
on:
  issues:
    types: [opened]
jobs:
  log:
    name: Log thing when new issue made
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Say Hi
        run: echo "Hello actions"
      - name: List files
        run: ls -l

